#!/bin/bash

DIR="$HOME/dotfiles"
DOTS_TO_LN=(".fehbg" ".hledger_accounts" ".urxvt" ".config/i3/config" ".config/ranger/rc.conf" ".config/i3blocks/config" ".Xresources.d" ".Xdefaults")

for dot in "${DOTS_TO_LN[@]}"; do
    rm -rf "$HOME/$dot"
    ln -sfT "$DIR/$dot" "$HOME/$dot"
done

source "$HOME/.bashrc"
