#!/bin/sh

ask() {
    printf "$1 [y/n] "
    read -rn 1
    echo
}

ask "Do you wish to install pacman packages?"
[ "$REPLY" = "y" ] && grep -v "#" pkgs-arch | sudo pacman -Syu --noconfirm -

dot_config_folders="    \
    autorandr           \
    git                 \
    mpd                 \
    mpv                 \
    nvim                \
    npm                 \
    python              \
    sxhkd               \
    sxiv                \
    fontconfig          \
"
for f in $dot_config_folders; do
    mkdir -p "$HOME/.config/$f"
done

mkdir -p "$HOME/.local/share/applications"

stow autorandr bash git mpd mpv ncmpcpp neovim vim newsboat npm python sxhkd sxiv x11 xdg latex

ask "Do you wish to install ruby packages?"
[ "$REPLY" = "y" ] && xargs -a pkgs-gem gem install

ask "Do you wish to install python packages?"
[ "$REPLY" = "y" ] && pip install --user -r pkgs-pip

ask "Do you wish to install npm packages?"
[ "$REPLY" = "y" ] && xargs -a pkgs-npm npm i -g

ask "Do you wish to install github packages?"
if [ "$REPLY" = "y" ]; then
    mkdir "$HOME/repos"
    for name in st dmenu dwm slock
    do
        git clone "https://github.com/andreafeletto/$name.git" "$HOME/repos/$name"
        (cd "$HOME/repos/$name" && sudo make install clean)
    done
fi
