#!/bin/sh

export FFF_HIDDEN=0

export FFF_KEY_SCROLL_UP2='off'
export FFF_KEY_SCROLL_DOWN2='off'
export FFF_KEY_PARENT2='off'
export FFF_KEY_CHILD2='off'

if command -v rmtrash > /dev/null 2>&1; then
	export FFF_TRASH_CMD='rmtrash'
else
	export FFF_TRASH_CMD='mv'
fi
