#!/bin/sh

PATH="$PATH:$HOME/.local/bin"
PATH="$PATH:$HOME/.local/cargo/bin"
PATH="$PATH:/usr/local/go/bin"
PATH="$PATH:$HOME/go/bin"
PATH="$PATH:$GEM_HOME"
PATH="$PATH:$XDG_DATA_HOME/npm/bin"
PATH="$PATH:/usr/local/plan9/bin"
PATH="$PATH:$ANDROID_HOME/platform-tools"
PATH="$PATH:$HOME/.emacs.d/bin"
PATH="$PATH:/usr/lib/w3m"
export PATH
