#!/bin/bash

while read file
do
    fullpath="$(pwd)/$file"
    case "$1" in
    "w")
        feh --bg-max "$file"
        notify-send -i "$file" "Wallpaper changed." ;;
    "r")
        convert -rotate 90 "$file" "$file" ;;
    "R")
        convert -rotate -90 "$file" "$file" ;;
    "f")
        convert -flop "$file" "$file" ;;
    "y")
        echo -n "$file" | xclip -selection clipboard &&
        notify-send "$file copied to clipboard" & ;;
    "Y")
        echo -n "$fullpath" | xclip -selection clipboard &&
        notify-send "$fullpath copied to clipboard" & ;;
    "d")
        [ "$(printf "No\\nYes" | dmenu -i -p "Really delete $file?")" = "Yes" ] && rm "$file" && notify-send "$file deleted." ;;
    esac
done
