#!/bin/bash

VALUE=`cat /sys/class/power_supply/BAT1/capacity` || exit
STATUS=`cat /sys/class/power_supply/BAT1/status`

# echo "`sed -e "s/,//g;s/Discharging/🔋/;s/Charging/🔌/;s/Unknown/❓/;s/Full/⚡/;s/ 0*/ /g;s/ :/ /g" <<<"$STATUS"` `sed -e 's/$/%/' <<<"$VALUE"`"

case $STATUS in
    "Discharging")
        ICON="🔋";;
    "Charging")
        ICON="🔌";;
    "Full")
        ICON="⚡";;
    "Unknown")
        ICON="❓";;
esac

echo "$ICON $VALUE%"
