#!/bin/sh

while true; do
    VALUE=`cat /sys/class/power_supply/BAT1/capacity`
    STATUS=`cat /sys/class/power_supply/BAT1/status`
    DATE=`date '+%Y %b %d (%a)  %I:%M%p'`
    xsetroot -name "$(i3ledger) | $(i3volume) | $(i3light) | $VALUE% | $DATE"
    sleep 2
done
