#!/bin/sh

while true; do
    VALUE=`cat /sys/class/power_supply/BAT1/capacity`
    STATUS=`cat /sys/class/power_supply/BAT1/status`
    DATE=`date '+%a %d %b %Y  %I:%M%p'`
    xsetroot -name "$(i3light) | $(i3volume) | $(i3battery) | $DATE"
    sleep 1
done
