#!/bin/sh

VALUE=$(cat /sys/class/power_supply/BAT1/capacity) || exit
STATUS=$(cat /sys/class/power_supply/BAT1/status)

case $STATUS in
    "Discharging")
        ICON="🔋";;
    "Charging")
        ICON="🔌";;
    "Full")
        ICON="⚡";;
    "Unknown")
        ICON="❓";;
esac

echo "$ICON $VALUE%"
