#!/bin/bash

case $BLOCK_BUTTON in
    1) notify-send 'Downloading...' -t 1000 && hld
esac

hledger bal --flat | grep -f $HOME/.hledger_accounts | awk '{ print $2, $1}' | awk -F ':' '{ print $NF }' | awk '{ print $1 ": " $2 }' | paste -sd ' '
