#!/bin/sh

rm -f /tmp/locked.png

[ -f /usr/bin/convert ] &&
scrot -m -z /tmp/base.png &&
convert /tmp/base.png -blur 0x8 /tmp/locked.png

i3lock -e -f -i /tmp/locked.png

sleep 10 && [ 4000 -lt "$(xssstate -i)" ] &&  pgrep -x i3lock && xset dpms force off
